# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160912_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Cargo'},
        ),
        migrations.AlterModelOptions(
            name='licensetype',
            options={'verbose_name': 'Tipo de Licencia'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Trabajador'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Viaje'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehículo'},
        ),
        migrations.AlterField(
            model_name='travel',
            name='departure_date',
            field=models.DateTimeField(default=datetime.date(2016, 9, 15), verbose_name='Fecha de Salida'),
        ),
    ]
