# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160915_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Salida'),
        ),
    ]
