# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160921_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(max_length=20, null=True, verbose_name=b'Latitud')),
                ('longitude', models.CharField(max_length=20, null=True, verbose_name=b'Longitud')),
                ('message', models.CharField(max_length=200, null=True, verbose_name=b'Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehiculo'},
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(verbose_name=b'Cumpleanos'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name=b'Ano'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_person', to='main.Person'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_vehicle', to='main.Vehicle'),
        ),
    ]
